PRODUCTS = {
    "bites": [
        {"name": "Almond Bite", "image": "almond_bite_new.png", "desc": "Premium almond sweet with rich taste.", "price": "₹1100/kg"},
        {"name": "Cashew Bite", "image": "cashew_bite_new.png", "desc": "Smooth cashew bite with classic flavor.", "price": "₹1150/kg"},
        {"name": "Chocolate Bite", "image": "chocolate_bite_new.png", "desc": "Delicious chocolate flavored sweet.", "price": "₹1200/kg"},
        {"name": "Fig Bite", "image": "fig_bite_new.png", "desc": "Naturally sweet fig bite treat.", "price": "₹1250/kg"},
        {"name": "Hazelnut Bite", "image": "hazelnut_bite_new.png", "desc": "Crunchy hazelnut bite with nutty aroma.", "price": "₹1100/kg"},
        {"name": "Pistachio Bite", "image": "pistachio_bite_new.png", "desc": "Premium pistachio bite, rich and smooth.", "price": "₹1150/kg"},
        {"name": "Rose Bite", "image": "rose_bite_new.png", "desc": "Fragrant rose-flavored traditional bite.", "price": "₹1200/kg"},
        {"name": "Mango Bite", "image": "mango_bite_new.png", "desc": "Tropical mango bite with fruity sweetness.", "price": "₹1250/kg"},
        {"name": "Lemon Bite", "image": "lemon_bite_new.png", "desc": "Zesty lemon bite with a fresh tang.", "price": "₹1100/kg"},
        {"name": "Orange Bite", "image": "orange_bite_new.png", "desc": "Citrus orange bite, bright and sweet.", "price": "₹1150/kg"},
        {"name": "Cranberry Bite", "image": "cranberry_bite_new.png", "desc": "Tart cranberry bite with berry notes.", "price": "₹1200/kg"},
        {"name": "Raspberry Bite", "image": "raspberry_bite_new.png", "desc": "Berry raspberry bite, soft and fruity.", "price": "₹1250/kg"},
        {"name": "Dry Fruit Bite", "image": "dry_fruite_bite.png", "desc": "Rich blend of premium dry fruits.", "price": "₹1300/kg"},
    ],
    "crunch": [
        {"name": "Nutty Crunch", "image": "nutty_crunch.jpg", "desc": "Crispy nutty crunch with premium dry fruits.", "price": "₹1100/kg"},
        {"name": "Coconut Crunch", "image": "coconut_crunch.jpg", "desc": "Light coconut crunch loved by all ages.", "price": "₹1150/kg"},
        {"name": "Chocolate Crunch", "image": "chocolate_crunch.png", "desc": "Rich chocolate crunch with bold flavor.", "price": "₹1200/kg"},
        {"name": "Hazelnut Crunch", "image": "hazelnut_crunch.jpg", "desc": "Premium hazelnut crunch with rich nuts.", "price": "₹1250/kg"},
        {"name": "Pistachio Crunch", "image": "pistachio_crunch.jpg", "desc": "Crisp pistachio crunch, nutty and light.", "price": "₹1100/kg"},
        {"name": "Caramel Crunch", "image": "caramel_crunch.jpg", "desc": "Golden caramel crunch with buttery taste.", "price": "₹1150/kg"},
        {"name": "Coffee Crunch", "image": "coffee_crunch.jpg", "desc": "Aromatic coffee crunch for bold palates.", "price": "₹1200/kg"},
        {"name": "Ginger Crunch", "image": "ginger_crunch.jpg", "desc": "Warm ginger crunch with spicy sweetness.", "price": "₹1250/kg"},
        {"name": "Lemon Crunch", "image": "lemon_crunch.jpg", "desc": "Zesty lemon crunch, crisp and fresh.", "price": "₹1100/kg"},
        {"name": "Orange Crunch", "image": "orange_crunch.jpg", "desc": "Citrus orange crunch with bright flavor.", "price": "₹1150/kg"},
        {"name": "Mint Crunch", "image": "mint_crunch.jpg", "desc": "Cool mint crunch, refreshing finish.", "price": "₹1200/kg"},
        {"name": "Cranberry Crunch", "image": "cranberry_crunch.jpg", "desc": "Tart cranberry crunch with berry crunch.", "price": "₹1250/kg"},
    ],
    "delight": [
        {"name": "Rose Delight", "image": "rose_delight.jpg", "desc": "Fragrant rose delight with premium taste.", "price": "₹1/kg"},
        {"name": "Almond Delight", "image": "almond_delight.png", "desc": "Rich and premium almond delight sweet.", "price": "₹1200/kg"},
        {"name": "Chocolate Delight", "image": "chocolate_delight.png", "desc": "Smooth chocolate delight for sweet lovers.", "price": "₹1250/kg"},
        {"name": "Coconut Delight", "image": "coconut_delight.png", "desc": "Soft coconut delight with tropical notes.", "price": "₹1100/kg"},
        {"name": "Mango Delight", "image": "mango_delight.png", "desc": "Fruity mango delight, summer favorite.", "price": "₹1250/kg"},
        {"name": "Lemon Delight", "image": "lemon_delight.png", "desc": "Zesty lemon delight with citrus freshness.", "price": "₹1100/kg"},
        {"name": "Orange Delight", "image": "orange_delight.png", "desc": "Bright orange delight with citrus sweetness.", "price": "₹1150/kg"},
        {"name": "Blueberry Delight", "image": "blueberry_delight.png", "desc": "Berry blueberry delight, soft and fruity.", "price": "₹1200/kg"},
        {"name": "Strawberry Delight", "image": "strawberry_delight.png", "desc": "Sweet strawberry delight, bursting with berry flavor.", "price": "₹1200/kg"},
        {"name": "Kachaa Aam Delight", "image": "kachaaam_delight.png", "desc": "Tangy raw mango delight with a sweet and sour kick.", "price": "₹1200/kg"},
    ],
    "mix": [
        {"name": "Assorted Diwali Box", "image": "assorted_box.jpg", "desc": "A premium selection of our best sweets.", "price": "₹1200/box"},
    ]
}
